version: '3'

# TODO: Replace root user and password to dynamicly values
services:
  sk-rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: "sk-rabbitmq"
    ports:
      - "15672:15672" # Management port
      - "5672:5672" # Service port
  sk-mysql:
    image: mysql:5.7
    container_name: "sk-mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/database/scripts/entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: skeduleApp
      MYSQL_ROOT_PASSWORD: root