userCache:
  type: caffeine
  cacheLifeTimeMillis: 300000 # 5 min
  cacheMaxSize: 100

auth:
  resourcesPackage: com.megapapa.sk.resource
  type: http
  debug: false

rabbitmq:
  connections:
    sk-auth:
      type: 'amqp'
      automaticRecoveryEnabled: true
      connectionTimeout: 60000
      handshakeTimeout: 60000
      host: localhost
      password: guest
      port: 5672
      username: guest
      virtualHost: /
  exchanges:
   sk-auth-exchange:
     autoDelete: false
     durable: true
     internal: true
     type: TOPIC
  queues:
   sk-auth:
     autoDelete: false
     durable: true
     exclusive: false

# Jetty config
jetty:
 connectors:
  - port: 8080
 context: /
 minThreads: 1
 maxThreads: 40

# JDBC config
jdbc:
 skedule:
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/skeduleApp?user=root&password=root&connectTimeout=0&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
  maximumPoolSize: 10
  minimumIdle: 1

# Cayenne configs
cayenne:
  datasource: skedule
  configs:
   - cayenne/cayenne-skedule.xml