package com.megapapa.sk.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.MongoUser;

/**
 * Class _BookReadTask was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BookReadTask extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ISBN = Property.create("isbn", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<MongoUser> MONGO_USER = Property.create("mongoUser", MongoUser.class);

    public void setIsbn(String isbn) {
        writeProperty("isbn", isbn);
    }
    public String getIsbn() {
        return (String)readProperty("isbn");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setMongoUser(MongoUser mongoUser) {
        setToOneTarget("mongoUser", mongoUser, true);
    }

    public MongoUser getMongoUser() {
        return (MongoUser)readProperty("mongoUser");
    }


}
