package com.megapapa.sk.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.AssignedTask;
import com.megapapa.sk.cayenne.Company;
import com.megapapa.sk.cayenne.TaskMessage;

/**
 * Class _CompanyTask was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CompanyTask extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<List<AssignedTask>> ASSIGNED_TASKS = Property.create("assignedTasks", List.class);
    public static final Property<Company> COMPANY = Property.create("company", Company.class);
    public static final Property<List<TaskMessage>> TASK_MESSAGES = Property.create("taskMessages", List.class);

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void addToAssignedTasks(AssignedTask obj) {
        addToManyTarget("assignedTasks", obj, true);
    }
    public void removeFromAssignedTasks(AssignedTask obj) {
        removeToManyTarget("assignedTasks", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AssignedTask> getAssignedTasks() {
        return (List<AssignedTask>)readProperty("assignedTasks");
    }


    public void setCompany(Company company) {
        setToOneTarget("company", company, true);
    }

    public Company getCompany() {
        return (Company)readProperty("company");
    }


    public void addToTaskMessages(TaskMessage obj) {
        addToManyTarget("taskMessages", obj, true);
    }
    public void removeFromTaskMessages(TaskMessage obj) {
        removeToManyTarget("taskMessages", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TaskMessage> getTaskMessages() {
        return (List<TaskMessage>)readProperty("taskMessages");
    }


}
