package com.megapapa.sk.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.Company;
import com.megapapa.sk.cayenne.MongoUser;

/**
 * Class _CompanyInvite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CompanyInvite extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String COMPANY_ID_PK_COLUMN = "company_id";
    public static final String MONGO_USER_ID_PK_COLUMN = "mongo_user_id";

    public static final Property<Boolean> IS_READED = Property.create("isReaded", Boolean.class);
    public static final Property<String> MESSAGE = Property.create("message", String.class);
    public static final Property<Company> COMPANY = Property.create("company", Company.class);
    public static final Property<MongoUser> MONGO_USER = Property.create("mongoUser", MongoUser.class);

    public void setIsReaded(boolean isReaded) {
        writeProperty("isReaded", isReaded);
    }
	public boolean isIsReaded() {
        Boolean value = (Boolean)readProperty("isReaded");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMessage(String message) {
        writeProperty("message", message);
    }
    public String getMessage() {
        return (String)readProperty("message");
    }

    public void setCompany(Company company) {
        setToOneTarget("company", company, true);
    }

    public Company getCompany() {
        return (Company)readProperty("company");
    }


    public void setMongoUser(MongoUser mongoUser) {
        setToOneTarget("mongoUser", mongoUser, true);
    }

    public MongoUser getMongoUser() {
        return (MongoUser)readProperty("mongoUser");
    }


}
