package com.megapapa.sk.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.CompanyTask;
import com.megapapa.sk.cayenne.Country;
import com.megapapa.sk.cayenne.MongoUser;

/**
 * Class _Company was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Company extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ADDRESS = Property.create("address", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<CompanyTask>> COMPANY_TASKS = Property.create("companyTasks", List.class);
    public static final Property<Country> COUNTRY = Property.create("country", Country.class);
    public static final Property<List<MongoUser>> MONGO_USERS = Property.create("mongoUsers", List.class);

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToCompanyTasks(CompanyTask obj) {
        addToManyTarget("companyTasks", obj, true);
    }
    public void removeFromCompanyTasks(CompanyTask obj) {
        removeToManyTarget("companyTasks", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CompanyTask> getCompanyTasks() {
        return (List<CompanyTask>)readProperty("companyTasks");
    }


    public void setCountry(Country country) {
        setToOneTarget("country", country, true);
    }

    public Country getCountry() {
        return (Country)readProperty("country");
    }


    public void addToMongoUsers(MongoUser obj) {
        addToManyTarget("mongoUsers", obj, true);
    }
    public void removeFromMongoUsers(MongoUser obj) {
        removeToManyTarget("mongoUsers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MongoUser> getMongoUsers() {
        return (List<MongoUser>)readProperty("mongoUsers");
    }


}
