package com.megapapa.sk.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.Company;

/**
 * Class _Country was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Country extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> SHORTNAME = Property.create("shortname", String.class);
    public static final Property<List<Company>> COMPANIES = Property.create("companies", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setShortname(String shortname) {
        writeProperty("shortname", shortname);
    }
    public String getShortname() {
        return (String)readProperty("shortname");
    }

    public void addToCompanies(Company obj) {
        addToManyTarget("companies", obj, true);
    }
    public void removeFromCompanies(Company obj) {
        removeToManyTarget("companies", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Company> getCompanies() {
        return (List<Company>)readProperty("companies");
    }


}
