package com.megapapa.sk.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.MongoUser;

/**
 * Class _Currency was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Currency extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> SHORTNAME = Property.create("shortname", String.class);
    public static final Property<String> SYMBOL = Property.create("symbol", String.class);
    public static final Property<List<MongoUser>> MONGO_USERS = Property.create("mongoUsers", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setShortname(String shortname) {
        writeProperty("shortname", shortname);
    }
    public String getShortname() {
        return (String)readProperty("shortname");
    }

    public void setSymbol(String symbol) {
        writeProperty("symbol", symbol);
    }
    public String getSymbol() {
        return (String)readProperty("symbol");
    }

    public void addToMongoUsers(MongoUser obj) {
        addToManyTarget("mongoUsers", obj, true);
    }
    public void removeFromMongoUsers(MongoUser obj) {
        removeToManyTarget("mongoUsers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MongoUser> getMongoUsers() {
        return (List<MongoUser>)readProperty("mongoUsers");
    }


}
