package com.megapapa.sk.cayenne.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.MongoUser;

/**
 * Class _Reminder was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Reminder extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATED_TIME = Property.create("createdTime", LocalDateTime.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<LocalDateTime> REMIND_TIME = Property.create("remindTime", LocalDateTime.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<String> TYPE = Property.create("type", String.class);
    public static final Property<MongoUser> MONGO_USER = Property.create("mongoUser", MongoUser.class);

    public void setCreatedTime(LocalDateTime createdTime) {
        writeProperty("createdTime", createdTime);
    }
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime)readProperty("createdTime");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setRemindTime(LocalDateTime remindTime) {
        writeProperty("remindTime", remindTime);
    }
    public LocalDateTime getRemindTime() {
        return (LocalDateTime)readProperty("remindTime");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setMongoUser(MongoUser mongoUser) {
        setToOneTarget("mongoUser", mongoUser, true);
    }

    public MongoUser getMongoUser() {
        return (MongoUser)readProperty("mongoUser");
    }


}
