package com.megapapa.sk.cayenne.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.megapapa.sk.cayenne.MultistepTask;

/**
 * Class _TaskStep was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TaskStep extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<LocalDateTime> END_TIME = Property.create("endTime", LocalDateTime.class);
    public static final Property<MultistepTask> MULTISTEP_TASK = Property.create("multistepTask", MultistepTask.class);

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setEndTime(LocalDateTime endTime) {
        writeProperty("endTime", endTime);
    }
    public LocalDateTime getEndTime() {
        return (LocalDateTime)readProperty("endTime");
    }

    public void setMultistepTask(MultistepTask multistepTask) {
        setToOneTarget("multistepTask", multistepTask, true);
    }

    public MultistepTask getMultistepTask() {
        return (MultistepTask)readProperty("multistepTask");
    }


}
